---
apiVersion: v1
kind: Kluge
metadata:
  name: aws-infra-apps
  labels:
    "bar!textfile": test.txt
    "bar64!base64file": test.txt
---
apiVersion: v1
kind: Junk
metadata:
  name: poopppy
content!textfile: test.txt
secret!base64file: test.bin
  
