---
# put this into a file in your kustomize directory
# and add filename to the list of transformers in
# the kustomize.yaml
apiVersion: kustomize-utils.dudinea.org/v1
kind: YamlIncludeTransformer
metadata:
  name: notImportantHere
